[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/__/auth/*"
  to = "https://gymlog-app-83f7f.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
